import { APP_NAME, APP_VERSION } from "@/lib/app";

export type AppRelease = {
  version: string;
  date: string;
  title: string;
  summary: string;
  changes: readonly string[];
};

export const APP_RELEASES: readonly AppRelease[] = [
  {
    version: "0.4.5",
    date: "2026-08-22",
    title: "Fiabilité du périmètre des comptes de gestion",
    summary: `${APP_NAME} sélectionne désormais les comptes et placements d’un compte de gestion selon leur période de présence, avec des exceptions manuelles justifiées et un périmètre durablement figé dans les documents générés.`,
    changes: [
      "Sélection automatique des comptes et placements selon leur période de présence",
      "Inclusion ou exclusion manuelle justifiée pendant la préparation",
      "Relevés et contrôles de complétude limités aux comptes réellement concernés",
      "Protection contre les comptes de gestion aux périodes chevauchantes",
      "Conservation du périmètre et des valeurs dans les projets générés et les documents finalisés",
    ],
  },
  {
    version: "0.4.4",
    date: "2026-08-22",
    title: "Approbation et signalement des comptes de gestion",
    summary: `${APP_NAME} permet désormais d’enregistrer le retour reçu après transmission d’un compte de gestion : approbation ou signalement d’une difficulté.`,
    changes: [
      "Déclaration d’une approbation après transmission",
      "Déclaration d’une difficulté après transmission",
      "Conservation de la date et des informations du retour",
      "Correction contrôlée des informations enregistrées",
      "Maintien du PDF officiel et de sa photographie réglementaire",
      "Consultation adaptée aux droits Propriétaire, Gestionnaire et Lecture seule",
    ],
  },
  {
    version: "0.4.3",
    date: "2026-08-19",
    title: "Fiabilité des valorisations et comptes de gestion",
    summary: "Correction des valorisations financières et renforcement de l’intégrité historique des comptes de gestion générés et finalisés.",
    changes: [
      "Correction de la date, de la valeur et du commentaire d’une valorisation existante",
      "Meilleure gestion des droits de modification et du cycle de vie des comptes",
      "Photographie figée des données lors de la génération d’un projet",
      "Conservation définitive des données utilisées lors de la finalisation",
      "Protection des anciens comptes de gestion contre les recalculs à partir de données modifiées ultérieurement",
    ],
  },
  {
    version: "0.4.2",
    date: "2026-08-18",
    title: "Transmission des comptes de gestion",
    summary: `${APP_NAME} permet désormais d’enregistrer la transmission d’un compte de gestion finalisé, avec date, mode, destinataire et note, tout en conservant le document officiel définitivement figé.`,
    changes: [
      "Déclaration de la transmission d’un compte de gestion finalisé",
      "Date métier et mode de transmission",
      "Destinataire et note facultative",
      "Nouveau statut Transmis",
      "Correction contrôlée des métadonnées de transmission",
      "Conservation du PDF officiel sans modification",
      "Droits adaptés aux rôles Propriétaire, Gestionnaire et Lecture seule",
    ],
  },
  {
    version: "0.4.1",
    date: "2026-08-16",
    title: "Maintenance des dépendances",
    summary: "Mise à jour de sécurité ciblée des dépendances techniques de PatriGest, sans modification fonctionnelle.",
    changes: [
      "Mise à jour ciblée d’une dépendance technique transitive",
      "Suppression de la vulnérabilité signalée par l’audit npm",
    ],
  },
  {
    version: "0.4.0",
    date: "2026-08-16",
    title: "Comptes de gestion réglementaires",
    summary: `${APP_NAME} prépare désormais le compte de gestion annuel à partir des données du dossier, contrôle sa complétude, calcule les ressources et dépenses selon le référentiel officiel, produit un aperçu réglementaire puis génère un PDF projet révisable avant finalisation du document officiel.`,
    changes: [
      "Création de comptes de gestion annuels sur une période réglementaire",
      "Contrôle progressif de la complétude du compte de gestion",
      "Prise en compte des données réglementaires de la personne et de la mesure",
      "Référentiel officiel de 18 ressources et 38 dépenses",
      "Rattachement des catégories personnelles aux catégories officielles",
      "Intégration des comptes, placements, relevés, biens immobiliers et dettes",
      "Aperçu réglementaire avant génération documentaire",
      "PDF projet révisable avec filigrane PROJET",
      "Reprise de la préparation possible tant que le document n’est pas finalisé",
      "PDF final sans filigrane et archivage dans un stockage privé",
      "Finalisation irréversible du document dans le flux normal",
    ],
  },
  {
    version: "0.3.9",
    date: "2026-08-15",
    title: "Relevés bancaires sécurisés",
    summary: `${APP_NAME} permet désormais d’archiver les relevés bancaires et documents de situation directement sur chaque compte, dans un stockage privé sécurisé, en préparation des futurs comptes de gestion.`,
    changes: [
      "Relevés rattachés directement aux comptes financiers",
      "Documents PDF privés limités à 10 Mo",
      "Consultation et téléchargement sécurisés",
      "Remplacement et suppression contrôlés des relevés",
      "Prise en charge des comptes courants, livrets, assurances-vie et autres placements",
      "Conservation indépendante des valorisations des placements",
      "Recherche du dernier relevé disponible à une date donnée",
      "Blocage de la suppression d’un compte tant qu’un relevé subsiste",
    ],
  },
  {
    version: "0.3.8",
    date: "2026-08-15",
    title: "Patrimoine immobilier et dettes",
    summary: `${APP_NAME} permet désormais de suivre les biens immobiliers, leurs événements significatifs, les dettes et l'historique daté de leur solde restant, en préparation des futurs comptes de gestion.`,
    changes: [
      "Gestion des biens immobiliers avec statut actif ou cédé",
      "Historique des événements immobiliers",
      "Fiche de consultation détaillée de chaque bien",
      "Gestion des dettes et emprunts",
      "Situations datées du solde restant des dettes",
      "Résumé courant synchronisé sur la situation la plus récente",
      "Prise en charge des saisies rétroactives",
      "Accès adaptés aux rôles Propriétaire, Gestionnaire et Lecture seule",
    ],
  },
  {
    version: "0.3.7",
    date: "2026-08-14",
    title: "Données réglementaires du dossier",
    summary: `${APP_NAME} complète les informations réglementaires de la personne protégée et de sa mesure de protection afin de préparer les futurs comptes de gestion.`,
    changes: [
      "Gestion du domicile et d’une résidence distincte",
      "Informations judiciaires avec numéro RG et cabinet",
      "Identification de la personne en charge de la mesure",
      "Date de nomination et coordonnées de la personne en charge",
      "Nouveaux types de mesure réglementaires",
      "Indicateurs de complétude du dossier",
      "Guidage visuel des champs restant à renseigner",
      "Traitement adapté du mandat de protection future",
    ],
  },
  {
    version: "0.3.6",
    date: "2026-08-14",
    title: "Référentiel officiel des catégories",
    summary: "Alignement des catégories de ressources et dépenses sur le modèle officiel du compte de gestion, avec rattachement des catégories personnelles et reclassement des opérations existantes.",
    changes: [
      "Référentiel structuré de 56 catégories officielles de ressources et dépenses",
      "Codes métier stables RES-* et DEP-* pour les futurs comptes de gestion",
      "Rattachement obligatoire des nouvelles catégories personnelles à une catégorie officielle compatible",
      "Présentation distincte et structurée des catégories officielles et personnelles",
      "Suggestion locale et déterministe du rattachement officiel",
      "Reclassement des opérations existantes vers le référentiel officiel",
      "Suppression des anciennes catégories système PatriGest",
      "Préparation du classement réglementaire des mouvements vers les placements sans modifier leur nature de virement",
    ],
  },
  {
    version: "0.3.5",
    date: "2026-08-13",
    title: "Suppressions contrôlées et nettoyage",
    summary: `${APP_NAME} permet désormais de supprimer proprement les opérations, comptes, dossiers et utilisateurs de test tout en protégeant les données encore liées et en évitant les suppressions en cascade non désirées.`,
    changes: [
      "Correction de la navigation après suppression d’une opération",
      "Retour automatique vers le registre ou le journal approprié",
      "Suppression d’une opération avec son justificatif",
      "Suppression contrôlée du fichier privé Storage associé",
      "Suppression d’un compte uniquement lorsqu’il est vide",
      "Refus clair lorsqu’un compte contient encore des données",
      "Suppression d’un dossier uniquement lorsqu’il est vide",
      "Refus clair lorsqu’un dossier contient encore des comptes ou des données liées",
      "Suppression administrative d’un utilisateur sans dossier ni accès métier",
      "Protection contre la suppression d’un utilisateur encore lié à des données",
      "Protection des comptes platform_admin",
      "Aucune suppression métier silencieuse en cascade",
    ],
  },
  {
    version: "0.3.4",
    date: "2026-08-12",
    title: "Registre des comptes et navigation financière",
    summary: `${APP_NAME} propose désormais un parcours financier centré sur le compte, avec un registre bancaire plus naturel, un solde progressif après chaque opération et une navigation simplifiée vers les opérations et les informations du compte.`,
    changes: [
      "Ouverture directe du registre lors d’un clic sur un compte bancaire",
      "Journal dédié aux opérations du compte",
      "Solde progressif après chaque opération, calculé sur l’historique complet indépendamment des filtres affichés",
      "Présentation distincte des dépenses et des recettes",
      "Virements intégrés au registre selon leur sens",
      "Lignes d’opération entièrement cliquables",
      "Actions Modifier et Supprimer déplacées sur la fiche de l’opération",
      "Consultation adaptée aux opérations clôturées et aux utilisateurs en lecture seule",
      "Bouton Informations du compte donnant accès à la fiche technique",
      "Création d’une opération depuis le registre avec le compte présélectionné",
      "Accès direct au mode Virement",
      "Interface desktop plus dense, proche d’un registre bancaire",
      "Cartes mobiles compactes et entièrement cliquables",
      "Parcours spécifique de valorisation conservé pour les placements",
    ],
  },
  {
    version: "0.3.3",
    date: "2026-08-12",
    title: "Justificatifs et gestion des placements",
    summary: `${APP_NAME} permet désormais de numéroter automatiquement les justificatifs de dépenses, de joindre des pièces privées aux opérations et de mieux distinguer les mouvements liés aux placements.`,
    changes: [
      "Saisie des opérations indépendante des exercices",
      "Création rétroactive des exercices",
      "Verrouillage des opérations lorsqu’un exercice est clôturé",
      "Réouverture contrôlée des exercices",
      "Interdiction du chevauchement des exercices",
      "Numérotation automatique des dépenses au format YYYY-NNNN, indépendante par dossier et par année",
      "Référence du justificatif figée après attribution",
      "Ajout de justificatifs PDF, JPEG et PNG dans un stockage privé",
      "Nom automatique des fichiers, par exemple : 2026-0042 - Pharmacie du Centre.pdf",
      "Consultation, téléchargement et remplacement des justificatifs selon les droits owner, manager et read_only",
      "Consultation en lecture seule des opérations ouvertes ou clôturées",
      "Assurances-vie et autres placements exclus des recettes et dépenses ordinaires",
      "Virements vers les placements identifiés comme Versement sur placement",
      "Virements depuis les placements identifiés comme Rachat de placement",
      "Valeur patrimoniale des placements conservée selon leur dernière valorisation",
      "Neutralité patrimoniale des virements internes avec placements",
      "Correction de la création de plusieurs dossiers par un même utilisateur",
    ],
  },
  {
    version: "0.3.2",
    date: "2026-08-10",
    title: "Accès multi-utilisateur et administration",
    summary: `${APP_NAME} permet désormais de gérer les demandes d’accès, les comptes utilisateurs et le partage sécurisé d’un dossier avec des collaborateurs en gestion ou en lecture seule.`,
    changes: [
      "Demande publique d’ouverture de compte",
      "Validation des demandes par le super administrateur",
      "Tableau de bord d’administration dédié",
      "Séparation stricte entre administrateur de plateforme et utilisateur métier",
      "Inscription uniquement après validation ou invitation",
      "Liens d’inscription sécurisés, expirables et régénérables",
      "Gestion des utilisateurs",
      "Invitation d’un collaborateur sur un dossier précis",
      "Rôles Gestionnaire et Lecture seule",
      "Gestion des accès au dossier et retrait immédiat d’un collaborateur",
      "Isolation complète des dossiers entre utilisateurs",
      "Protection RLS adaptée au multi-utilisateur",
      "Accès partagé aux comptes, opérations, valorisations et exercices selon le rôle",
      "Protection des données financières contre l’accès de l’administrateur de plateforme",
    ],
  },
  {
    version: "0.3.1",
    date: "2026-08-09",
    title: "Navigation et ergonomie",
    summary: `${APP_NAME} propose une navigation privée repensée et une interface plus compacte, cohérente et responsive sur l’ensemble des pages métier.`,
    changes: [
      "Nouvelle sidebar de navigation sur desktop et tiroir adapté au mobile",
      "Navigation contextuelle du dossier en cours",
      "Accès direct à Comptes et patrimoine",
      'Ajout de "Gérer les dossiers" pour consulter la liste et créer d’autres dossiers',
      "Réorganisation du dossier : Comptes et patrimoine, Opérations, Exercices de gestion et Informations du dossier",
      "Fil d’Ariane harmonisé et compacté",
      "Densification générale de l’interface privée et harmonisation des titres",
      "Cartes et formulaires plus compacts sur desktop et mobile",
      "Harmonisation des pages Comptes, Opérations, Catégories, Exercices, Informations du dossier et Historique des versions",
      "Journal des opérations, filtres et soldes actuels densifiés",
      `Réouverture contrôlée d’un exercice clôturé avec un dialogue ${APP_NAME}`,
      "Amélioration responsive générale",
    ],
  },
  {
    version: "0.3.0",
    date: "2026-08-09",
    title: "Opérations financières",
    summary: `${APP_NAME} permet désormais de saisir et suivre les recettes, dépenses et virements internes, avec calcul automatique des soldes et contrôle des exercices de gestion.`,
    changes: [
      "Saisie des recettes et dépenses",
      "Virements internes entre comptes",
      "Calcul automatique des soldes",
      "Journal des opérations avec filtres",
      "Catégories système et personnalisées",
      "Catégories utilisables en recettes, dépenses ou les deux",
      "Archivage et réactivation des catégories personnelles",
      "Gestion des exercices de gestion",
      "Verrouillage des opérations sur exercices clôturés",
      "Affichage du patrimoine actuel et des soldes sur la page Opérations",
      "Dernières opérations réelles sur le tableau de bord",
      "Tableau de bord compact et responsive",
      "Fil d’Ariane sur les principales pages métier",
    ],
  },
  {
    version: "0.2.0",
    date: "2026-08-08",
    title: "Comptes et patrimoine",
    summary: `${APP_NAME} permet désormais de gérer les comptes bancaires, les livrets et les placements d'une personne protégée.`,
    changes: [
      "Création et modification des comptes financiers",
      "Gestion des comptes courants et livrets",
      "Gestion des assurances-vie et autres placements",
      "Valorisation des placements",
      "Calcul automatique du patrimoine actif",
      "Clôture et réouverture des comptes",
      'Navigation dédiée "Comptes et patrimoine"',
      "Contrôles de sécurité par dossier",
      `Amélioration des confirmations avec les dialogues ${APP_NAME}`,
    ],
  },
  {
    version: "0.1.0",
    date: "2026-08-07",
    title: `Première version de ${APP_NAME}`,
    summary: `Les fondations de ${APP_NAME} sont en place.`,
    changes: [
      "Page d’accueil publique",
      "Inscription et connexion sécurisées",
      "Gestion des mots de passe",
      "Création des dossiers de personnes protégées",
      "Gestion des mesures de protection",
      "Gestion des exercices de gestion",
      "Tableau de bord privé",
      "Versionnement de l’application",
    ],
  },
];

export const LATEST_RELEASE = APP_RELEASES[0];

if (LATEST_RELEASE.version !== APP_VERSION) {
  throw new Error(
    `La version la plus récente (${LATEST_RELEASE.version}) doit correspondre à APP_VERSION (${APP_VERSION}).`,
  );
}
