import Link from "next/link";
import { Clock3, MailCheck, UserRoundCheck } from "lucide-react";
import { getAdministrationDashboardData } from "../services/administration-service";

export async function AdministrationDashboard() {
  const data = await getAdministrationDashboardData();
  return <><header><p className="text-xs font-bold uppercase tracking-[0.12em] text-[#2563EB]">Administration</p><h1 className="mt-1 text-2xl font-bold tracking-tight">Tableau de bord</h1><p className="mt-1 text-sm text-[#64748B]">Pilotez les accès à la plateforme PatriGest.</p></header><section className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3" aria-label="Indicateurs administratifs"><AdminStatCard href="/administration/utilisateurs" label="Utilisateurs" value={data.usersCount} detail="comptes utilisateurs" icon={UserRoundCheck} color="blue" /><AdminStatCard href="/administration/demandes" label="Demandes en attente" value={data.pendingRequestsCount} detail="à examiner" icon={MailCheck} color="orange" /><AdminStatCard label="Invitations en attente" value={data.pendingInvitationsCount} detail="valides et non acceptées" icon={Clock3} color="violet" /></section><section className="mt-4 rounded-xl border border-[#E2E8F0] bg-white p-4 shadow-[0_6px_18px_rgba(15,23,42,0.035)]"><div className="flex items-center justify-between gap-3"><h2 className="text-base font-bold">À traiter</h2>{data.pendingRequests.length > 0 && <Link href="/administration/demandes" className="text-xs font-semibold text-[#2563EB]">Voir toutes les demandes</Link>}</div>{data.pendingRequests.length > 0 ? <div className="mt-2 divide-y divide-[#E2E8F0]">{data.pendingRequests.map((request) => <Link key={request.id} href="/administration/demandes" className="focus-ring flex flex-col gap-0.5 rounded-lg py-2.5 transition hover:bg-slate-50 sm:flex-row sm:items-center sm:justify-between sm:px-2"><span><span className="block text-sm font-semibold">{request.first_name} {request.last_name}</span><span className="block text-xs text-[#64748B]">{request.email}</span></span><span className="text-xs text-[#94A3B8]">{new Intl.DateTimeFormat("fr-FR", { dateStyle: "short" }).format(new Date(request.created_at))}</span></Link>)}</div> : <div className="py-6 text-center"><p className="text-sm font-semibold">Aucune demande en attente</p><p className="mt-1 text-xs text-[#64748B]">Les nouvelles demandes apparaîtront ici.</p></div>}</section></>;
}

const colors = { blue: "bg-blue-50 text-[#2563EB]", orange: "bg-orange-50 text-[#EA580C]", violet: "bg-violet-50 text-[#7C3AED]" } as const;
function AdminStatCard({ href, label, value, detail, icon: Icon, color }: { href?: string; label: string; value: number; detail: string; icon: typeof UserRoundCheck; color: keyof typeof colors }) { const content = <div className="flex items-center gap-3"><span className={`flex size-9 shrink-0 items-center justify-center rounded-lg ${colors[color]}`}><Icon aria-hidden="true" size={18} /></span><span><span className="block text-xs font-semibold text-[#64748B]">{label}</span><span className="mt-0.5 block text-2xl font-bold leading-7">{value}</span><span className="block text-[11px] text-[#94A3B8]">{detail}</span></span></div>; return href ? <Link href={href} className="focus-ring rounded-xl border border-[#E2E8F0] bg-white p-4 shadow-[0_6px_18px_rgba(15,23,42,0.035)] transition hover:border-blue-200">{content}</Link> : <article className="rounded-xl border border-[#E2E8F0] bg-white p-4 shadow-[0_6px_18px_rgba(15,23,42,0.035)]">{content}</article>; }
