import type { Category, FinancialAccount, Transaction, TransactionDocument, Transfer } from "@/types/database";
import { isValuationAccount } from "@/domains/financial-accounts/utils/financial-account-utils";
import { getAuthenticatedUser } from "@/domains/protected-persons/services/authenticated-user";
import type { TransactionFilters, TransactionInput } from "../schemas/transaction-schema";
import { CLOSED_PERIOD_ERROR } from "../errors";

export type TransactionJournalItem = Transaction & { account: FinancialAccount; category: Category | null; transfer: Transfer | null; counterpartAccount: FinancialAccount | null };
async function ownedPerson(id: string) { const auth = await getAuthenticatedUser(); const { data } = await auth.supabase.from("protected_persons").select("id").eq("id", id).maybeSingle(); if (!data) throw new Error("Dossier introuvable."); return auth; }
async function ownedAccount(id: string, personId?: string) { const auth = await getAuthenticatedUser(); const { data: account } = await auth.supabase.from("financial_accounts").select("*").eq("id", id).maybeSingle(); if (!account || (personId && account.protected_person_id !== personId)) throw new Error("Compte introuvable."); const { data: person } = await auth.supabase.from("protected_persons").select("id").eq("id", account.protected_person_id).maybeSingle(); if (!person) throw new Error("Compte introuvable."); return { ...auth, account }; }
function validDate(account: FinancialAccount, date: string) { return date >= account.initial_balance_date && (!account.opening_date || date >= account.opening_date) && (!account.closing_date || date <= account.closing_date); }
async function validateCategory(supabase: Awaited<ReturnType<typeof getAuthenticatedUser>>["supabase"], userId: string, categoryId: string | null, type: "income" | "expense") { if (!categoryId) return; const { data } = await supabase.from("categories").select("*").eq("id", categoryId).eq("active", true).maybeSingle(); if (!data || (!data.is_system && data.owner_id !== userId) || (data.usage !== type && data.usage !== "both")) throw new Error("Catégorie incompatible."); }
async function ensureDateIsNotClosed(supabase: Awaited<ReturnType<typeof getAuthenticatedUser>>["supabase"], personId: string, date: string) { const { data } = await supabase.from("management_periods").select("id").eq("protected_person_id", personId).eq("status", "closed").lte("start_date", date).gte("end_date", date).limit(1); if (data?.length) throw new Error("Cette opération appartient à un exercice clôturé."); }

export async function getTransactions(personId: string, filters: TransactionFilters = {}): Promise<TransactionJournalItem[]> { const { supabase } = await ownedPerson(personId); const { data: accounts, error: ae } = await supabase.from("financial_accounts").select("*").eq("protected_person_id", personId); if (ae) throw new Error("Impossible de charger les comptes."); if (!accounts.length) return []; let query = supabase.from("transactions").select("*").in("financial_account_id", accounts.map((a) => a.id)).order("transaction_date", { ascending: false }).order("created_at", { ascending: false }); if (filters.startDate) query = query.gte("transaction_date", filters.startDate); if (filters.endDate) query = query.lte("transaction_date", filters.endDate); if (filters.accountId) query = query.eq("financial_account_id", filters.accountId); if (filters.type) query = filters.type === "transfer" ? query.in("transaction_type", ["transfer_in", "transfer_out"]) : query.eq("transaction_type", filters.type); if (filters.categoryId) query = query.eq("category_id", filters.categoryId); if (filters.query) query = query.ilike("label", `%${filters.query.replace(/[%_]/g, "")}%`); const { data, error } = await query; if (error) throw new Error("Impossible de charger les opérations."); const categoryIds = [...new Set(data.map((t) => t.category_id).filter((id): id is string => Boolean(id)))]; const transferIds = [...new Set(data.map((t) => t.transfer_id).filter((id): id is string => Boolean(id)))]; const [categories, transfers] = await Promise.all([categoryIds.length ? supabase.from("categories").select("*").in("id", categoryIds).then(({ data: rows }) => rows ?? []) : [], transferIds.length ? supabase.from("transfers").select("*").in("id", transferIds).then(({ data: rows }) => rows ?? []) : []]); return data.map((transaction) => { const transfer = transaction.transfer_id ? transfers.find((entry) => entry.id === transaction.transfer_id) ?? null : null; const counterpartId = transfer ? transaction.financial_account_id === transfer.source_account_id ? transfer.destination_account_id : transfer.source_account_id : null; return { ...transaction, account: accounts.find((account) => account.id === transaction.financial_account_id)!, category: categories.find((category) => category.id === transaction.category_id) ?? null, transfer, counterpartAccount: counterpartId ? accounts.find((account) => account.id === counterpartId) ?? null : null }; }); }
export async function getTransaction(id: string) { const auth = await getAuthenticatedUser(); const { data } = await auth.supabase.from("transactions").select("*").eq("id", id).maybeSingle(); if (!data) return null; try { const { account } = await ownedAccount(data.financial_account_id); return { ...data, account }; } catch { return null; } }
export async function createTransaction(personId: string, input: TransactionInput) { const { supabase, userId, account } = await ownedAccount(input.financialAccountId, personId); if (isValuationAccount(account.account_type)) throw new Error("Les recettes et dépenses nécessitent un compte transactionnel."); if (!validDate(account, input.transactionDate)) throw new Error("Date incompatible avec le compte."); await validateCategory(supabase, userId, input.categoryId, input.transactionType); const { data, error } = await supabase.from("transactions").insert({ financial_account_id: input.financialAccountId, transaction_date: input.transactionDate, transaction_type: input.transactionType, label: input.label, amount: input.amount, category_id: input.categoryId, proof_reference: null, comment: input.comment }).select("id,proof_reference").single(); if (error?.message.toLocaleLowerCase("fr-FR").includes("exercice clôturé")) throw new Error(CLOSED_PERIOD_ERROR); if (error) throw new Error(error.message.includes("année") ? error.message : "Impossible de créer l’opération."); if (!data) throw new Error("Impossible de confirmer la création de l’opération."); return data; }
export async function updateTransaction(id: string, personId: string, input: TransactionInput) { const existing = await getTransaction(id); if (!existing || existing.transfer_id || existing.account.protected_person_id !== personId) throw new Error("Opération introuvable."); const { supabase, userId, account } = await ownedAccount(input.financialAccountId, personId); if (isValuationAccount(account.account_type)) throw new Error("Les recettes et dépenses nécessitent un compte transactionnel."); await ensureDateIsNotClosed(supabase, personId, existing.transaction_date); await ensureDateIsNotClosed(supabase, personId, input.transactionDate); if (!validDate(account, input.transactionDate)) throw new Error("Date incompatible avec le compte."); await validateCategory(supabase, userId, input.categoryId, input.transactionType); const { error } = await supabase.from("transactions").update({ financial_account_id: input.financialAccountId, transaction_date: input.transactionDate, transaction_type: input.transactionType, label: input.label, amount: input.amount, category_id: input.categoryId, proof_reference: existing.proof_reference, comment: input.comment }).eq("id", id); if (error?.message.toLocaleLowerCase("fr-FR").includes("exercice clôturé")) throw new Error(CLOSED_PERIOD_ERROR); if (error) throw new Error(error.message.includes("année") ? error.message : "Impossible de modifier l’opération."); }

export async function getTransactionDocument(transactionId: string): Promise<TransactionDocument | null> { const { supabase } = await getAuthenticatedUser(); const { data, error } = await supabase.from("transaction_documents").select("*").eq("transaction_id", transactionId).maybeSingle(); if (error) throw new Error("Impossible de charger le justificatif."); return data; }
export async function deleteTransaction(id: string, personId: string) { const existing = await getTransaction(id); if (!existing || existing.transfer_id || existing.account.protected_person_id !== personId) throw new Error("Opération introuvable."); const { supabase } = await ownedPerson(personId); await ensureDateIsNotClosed(supabase, personId, existing.transaction_date); const { error } = await supabase.from("transactions").delete().eq("id", id); if (error?.message.toLocaleLowerCase("fr-FR").includes("exercice clôturé")) throw new Error(CLOSED_PERIOD_ERROR); if (error) throw new Error("Impossible de supprimer l’opération."); }
