"use server";
import { revalidatePath } from "next/cache";import { z } from "zod";import { debtBalanceSchema,debtSchema,propertyEventSchema,propertySchema } from "./schemas";import { addDebtBalance,addPropertyEvent,saveDebt,saveProperty } from "./services";import type { AssetLiabilityActionState } from "./state";
const ids=(...v:string[])=>v.every(id=>z.uuid().safeParse(id).success);const get=(f:FormData,n:string)=>f.get(n);const invalid=(e:z.ZodError):AssetLiabilityActionState=>({status:"error",message:"Vérifiez les informations saisies.",fieldErrors:e.flatten().fieldErrors});const refresh=(id:string)=>{revalidatePath(`/dossiers/${id}`);revalidatePath(`/dossiers/${id}/patrimoine-immobilier`);revalidatePath(`/dossiers/${id}/dettes`);};
const propertyValues=(f:FormData)=>({propertyType:get(f,"propertyType"),designation:get(f,"designation"),addressLine1:get(f,"addressLine1"),addressLine2:get(f,"addressLine2"),postalCode:get(f,"postalCode"),city:get(f,"city"),country:get(f,"country"),entryDate:get(f,"entryDate"),entryMode:get(f,"entryMode"),estimatedValue:get(f,"estimatedValue"),valuationDate:get(f,"valuationDate"),status:get(f,"status"),disposalDate:get(f,"disposalDate"),notes:get(f,"notes")});
const debtValues=(f:FormData)=>({creditor:get(f,"creditor"),debtType:get(f,"debtType"),designation:get(f,"designation"),startDate:get(f,"startDate"),initialAmount:get(f,"initialAmount"),initialDurationMonths:get(f,"initialDurationMonths"),monthlyPayment:get(f,"monthlyPayment"),interestRate:get(f,"interestRate"),status:get(f,"status"),settledAt:get(f,"settledAt"),notes:get(f,"notes")});
export async function savePropertyAction(personId:string,id:string|null,_:AssetLiabilityActionState,f:FormData):Promise<AssetLiabilityActionState>{if(!ids(personId)||id&&!ids(id))return{status:"error",message:"Bien invalide."};const p=propertySchema.safeParse(propertyValues(f));if(!p.success)return invalid(p.error);try{await saveProperty(personId,p.data,id??undefined);refresh(personId);return{status:"success",message:"Bien immobilier enregistré."};}catch(e){return{status:"error",message:e instanceof Error?e.message:"Échec de l’enregistrement."};}}
export async function addPropertyEventAction(personId:string,id:string,_:AssetLiabilityActionState,f:FormData):Promise<AssetLiabilityActionState>{if(!ids(personId,id))return{status:"error",message:"Bien invalide."};const p=propertyEventSchema.safeParse({eventType:get(f,"eventType"),eventDate:get(f,"eventDate"),description:get(f,"description"),amount:get(f,"amount"),documentReference:get(f,"documentReference")});if(!p.success)return invalid(p.error);try{await addPropertyEvent(personId,id,p.data);refresh(personId);return{status:"success",message:"Événement enregistré."};}catch(e){return{status:"error",message:e instanceof Error?e.message:"Échec de l’enregistrement."};}}
export async function saveDebtAction(personId:string,id:string|null,_:AssetLiabilityActionState,f:FormData):Promise<AssetLiabilityActionState>{if(!ids(personId)||id&&!ids(id))return{status:"error",message:"Dette invalide."};const p=debtSchema.safeParse(debtValues(f));if(!p.success)return invalid(p.error);try{await saveDebt(personId,p.data,id??undefined);refresh(personId);return{status:"success",message:"Dette enregistrée."};}catch(e){return{status:"error",message:e instanceof Error?e.message:"Échec de l’enregistrement."};}}
export async function addDebtBalanceAction(personId:string,id:string,_:AssetLiabilityActionState,f:FormData):Promise<AssetLiabilityActionState>{if(!ids(personId,id))return{status:"error",message:"Dette invalide."};const p=debtBalanceSchema.safeParse({balanceDate:get(f,"balanceDate"),remainingBalance:get(f,"remainingBalance"),remainingDurationMonths:get(f,"remainingDurationMonths")});if(!p.success)return invalid(p.error);try{await addDebtBalance(personId,id,p.data);refresh(personId);return{status:"success",message:"Situation enregistrée."};}catch(e){return{status:"error",message:e instanceof Error?e.message:"Échec de l’enregistrement."};}}
