import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { z } from "zod";
import { CalendarDays, FilePenLine, Landmark, TrendingUp } from "lucide-react";
import { PrivateShell } from "@/components/layout/private-shell";
import { CloseAccountForm, ReopenAccountForm, ValuationForm } from "@/domains/financial-accounts/components/account-actions";
import { getFinancialAccount } from "@/domains/financial-accounts/services/financial-account-service";
import { financialAccountLabels, formatCurrency, formatFinancialDate, getCurrentAccountValue, isValuationAccount } from "@/domains/financial-accounts/utils/financial-account-utils";
import { DossierNavigation } from "@/domains/protected-persons/components/dossier-navigation";
import { getProtectedPerson } from "@/domains/protected-persons/services/protected-person-service";

export const metadata: Metadata = { title: "Fiche compte" };
export const dynamic = "force-dynamic";

export default async function FinancialAccountDetailPage({ params }: { params: Promise<{ protectedPersonId: string; accountId: string }> }) {
  const { protectedPersonId, accountId } = await params;
  if (![protectedPersonId, accountId].every((id) => z.uuid().safeParse(id).success)) notFound();
  const [person, account] = await Promise.all([getProtectedPerson(protectedPersonId), getFinancialAccount(accountId)]);
  if (!person || !account || account.protected_person_id !== protectedPersonId) notFound();
  const current = getCurrentAccountValue(account, account.valuations);
  const minimumClosingDate = [account.initial_balance_date, account.opening_date].filter((value): value is string => Boolean(value)).sort().at(-1) ?? account.initial_balance_date;
  return <PrivateShell current="dossiers"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-[0.14em] text-[#2563EB]">{person.first_name} {person.last_name}</p><h1 className="mt-2 text-3xl font-bold">{account.account_name}</h1><p className="mt-2 text-[#64748B]">{account.institution_name}</p></div><Link href={`/dossiers/${protectedPersonId}/comptes/${accountId}/modifier`} className="button button-secondary gap-2"><FilePenLine aria-hidden="true" size={17} />Modifier</Link></div><DossierNavigation protectedPersonId={protectedPersonId} current="accounts" />
    <div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-[#E2E8F0] bg-white p-6"><Landmark aria-hidden="true" className="text-[#2563EB]" size={22} /><p className="mt-4 text-sm text-[#64748B]">Valeur actuelle</p><p className="mt-1 text-3xl font-bold">{formatCurrency(current.value)}</p>{current.valuation && <p className="mt-1 text-xs text-[#94A3B8]">Valorisation au {formatFinancialDate(current.valuation.valuation_date)}</p>}</section><section className="rounded-2xl border border-[#E2E8F0] bg-white p-6"><h2 className="text-lg font-bold">Informations</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2"><Data label="Type" value={financialAccountLabels[account.account_type]} /><Data label="Statut" value={account.status === "active" ? "Actif" : "Clôturé"} /><Data label="Solde initial" value={formatCurrency(account.initial_balance)} /><Data label="Date du solde" value={formatFinancialDate(account.initial_balance_date)} />{account.opening_date && <Data label="Date d’ouverture" value={formatFinancialDate(account.opening_date)} />}{account.account_reference && <Data label="Référence" value={account.account_reference} />}{account.closing_date && <Data label="Date de clôture" value={formatFinancialDate(account.closing_date)} />}</dl>{account.notes && <p className="mt-5 border-t border-[#E2E8F0] pt-4 text-sm leading-6 text-[#64748B]">{account.notes}</p>}</section></div>
    {isValuationAccount(account.account_type) && <section className="mt-8 rounded-2xl border border-[#E2E8F0] bg-white p-6 sm:p-8"><div className="flex items-center gap-3"><TrendingUp aria-hidden="true" className="text-[#0EA5E9]" size={21} /><h2 className="text-xl font-bold">Valorisations</h2></div>{account.valuations.length ? <div className="mt-5 overflow-x-auto"><table className="w-full min-w-lg text-left text-sm"><thead className="text-[#64748B]"><tr><th className="pb-3">Date</th><th className="pb-3">Valeur</th><th className="pb-3">Commentaire</th></tr></thead><tbody className="divide-y divide-[#E2E8F0]">{account.valuations.map((valuation) => <tr key={valuation.id}><td className="py-3">{formatFinancialDate(valuation.valuation_date)}</td><td className="py-3 font-semibold">{formatCurrency(valuation.value)}</td><td className="py-3 text-[#64748B]">{valuation.comment || "—"}</td></tr>)}</tbody></table></div> : <p className="mt-4 text-sm text-[#64748B]">Aucune valorisation enregistrée.</p>}<details className="mt-6"><summary className="button button-secondary cursor-pointer list-none">Ajouter une valorisation</summary><ValuationForm protectedPersonId={protectedPersonId} accountId={accountId} /></details></section>}
    <section className="mt-8 rounded-2xl border border-[#E2E8F0] bg-white p-6"><div className="flex items-center gap-3"><CalendarDays aria-hidden="true" className="text-[#EA580C]" size={20} /><h2 className="text-lg font-bold">Cycle de vie du compte</h2></div>{account.status === "active" ? <div className="mt-5"><CloseAccountForm protectedPersonId={protectedPersonId} accountId={accountId} accountName={account.account_name} minimumDate={minimumClosingDate} /></div> : <div className="mt-5"><p className="mb-4 text-sm text-[#64748B]">Ce compte est clôturé et exclu du patrimoine actif.</p><ReopenAccountForm protectedPersonId={protectedPersonId} accountId={accountId} accountName={account.account_name} /></div>}</section>
  </PrivateShell>;
}
function Data({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-semibold uppercase tracking-wide text-[#94A3B8]">{label}</dt><dd className="mt-1 text-[#334155]">{value}</dd></div>; }
